blank_issues_enabled: false
contact_links:
  - name: General discussion / ideas
    url: https://github.com/spotswoods/blenderpage/discussions
    about: Got a general idea, question, or want to chat about the direction of the site?
